#!/bin/bash

python scripts/find_errors.py mismatches/AC_6xPCR_no_ISceI_rep1_seq.txt.gz
python scripts/find_errors.py mismatches/AC_6xPCR_no_ISceI_rep2_seq.txt.gz
python scripts/find_errors.py mismatches/AC_6xPCR_no_ISceI_rep3_seq.txt.gz
python scripts/find_errors.py mismatches/AC_6xPCR_no_ISceI_rep4_seq.txt.gz
python scripts/find_errors.py mismatches/AC_6xPCR_no_ISceI_rep5_seq.txt.gz
python scripts/find_errors.py mismatches/AC_6xPCR_no_ISceI_rep6_seq.txt.gz
python scripts/find_errors.py mismatches/AC_6xPCR_no_ISceI_rep7_seq.txt.gz
python scripts/find_errors.py mismatches/AC_6xPCR_no_ISceI_rep8_seq.txt.gz
python scripts/find_errors.py mismatches/AC_6xPCR_no_ISceI_rep9_seq.txt.gz
python scripts/find_errors.py mismatches/AC_LA_no_ISceI_rep1_seq.txt.gz
python scripts/find_errors.py mismatches/AC_LA_no_ISceI_rep2_seq.txt.gz
python scripts/find_errors.py mismatches/AC_LA_no_ISceI_rep3_seq.txt.gz
python scripts/find_errors.py mismatches/AC_LA_no_ISceI_rep4_seq.txt.gz
python scripts/find_errors.py mismatches/AG_6xPCR_no_ISceI_rep1_seq.txt.gz
python scripts/find_errors.py mismatches/AG_6xPCR_no_ISceI_rep2_seq.txt.gz
python scripts/find_errors.py mismatches/AG_6xPCR_no_ISceI_rep3_seq.txt.gz
python scripts/find_errors.py mismatches/AG_6xPCR_no_ISceI_rep4_seq.txt.gz
python scripts/find_errors.py mismatches/AG_6xPCR_no_ISceI_rep5_seq.txt.gz
python scripts/find_errors.py mismatches/AG_6xPCR_no_ISceI_rep6_seq.txt.gz
python scripts/find_errors.py mismatches/AG_6xPCR_no_ISceI_rep7_seq.txt.gz
python scripts/find_errors.py mismatches/AG_LA_no_ISceI_rep1_seq.txt.gz
python scripts/find_errors.py mismatches/AG_LA_no_ISceI_rep2_seq.txt.gz
python scripts/find_errors.py mismatches/AG_LA_no_ISceI_rep3_seq.txt.gz
python scripts/find_errors.py mismatches/AG_LA_no_ISceI_rep4_seq.txt.gz
python scripts/find_errors.py mismatches/AG_LA_no_ISceI_rep5_seq.txt.gz
python scripts/find_errors.py mismatches/AG_LA_no_ISceI_rep6_seq.txt.gz
python scripts/find_errors.py mismatches/AG_LA_no_ISceI_rep7_seq.txt.gz
python scripts/find_errors.py mismatches/AG_LA_no_ISceI_rep8_seq.txt.gz
python scripts/find_errors.py mismatches/GT_6xPCR_no_ISceI_rep1_seq.txt.gz
python scripts/find_errors.py mismatches/GT_6xPCR_no_ISceI_rep2_seq.txt.gz
python scripts/find_errors.py mismatches/GT_6xPCR_no_ISceI_rep3_seq.txt.gz
python scripts/find_errors.py mismatches/GT_6xPCR_no_ISceI_rep4_seq.txt.gz
python scripts/find_errors.py mismatches/GT_LA_no_ISceI_rep1_seq.txt.gz
python scripts/find_errors.py mismatches/GT_LA_no_ISceI_rep2_seq.txt.gz
python scripts/find_errors.py mismatches/GT_LA_no_ISceI_rep3_seq.txt.gz
python scripts/find_errors.py mismatches/GT_LA_no_ISceI_rep4_seq.txt.gz
python scripts/find_errors.py mismatches/TC_6xPCR_no_ISceI_rep1_seq.txt.gz
python scripts/find_errors.py mismatches/TC_6xPCR_no_ISceI_rep2_seq.txt.gz
python scripts/find_errors.py mismatches/TC_6xPCR_no_ISceI_rep3_seq.txt.gz
python scripts/find_errors.py mismatches/TC_6xPCR_no_ISceI_rep4_seq.txt.gz
python scripts/find_errors.py mismatches/TC_6xPCR_no_ISceI_rep5_seq.txt.gz
python scripts/find_errors.py mismatches/TC_6xPCR_no_ISceI_rep6_seq.txt.gz
python scripts/find_errors.py mismatches/TC_6xPCR_no_ISceI_rep7_seq.txt.gz
python scripts/find_errors.py mismatches/TC_6xPCR_no_ISceI_rep8_seq.txt.gz
python scripts/find_errors.py mismatches/TC_LA_no_ISceI_rep1_seq.txt.gz
python scripts/find_errors.py mismatches/TC_LA_no_ISceI_rep2_seq.txt.gz
python scripts/find_errors.py mismatches/TC_LA_no_ISceI_rep3_seq.txt.gz
python scripts/find_errors.py mismatches/TC_LA_no_ISceI_rep4_seq.txt.gz
python scripts/find_errors.py mismatches/TC_LA_no_ISceI_rep5_seq.txt.gz
python scripts/find_errors.py mismatches/TC_LA_no_ISceI_rep6_seq.txt.gz
python scripts/find_errors.py mismatches/TC_LA_no_ISceI_rep7_seq.txt.gz
python scripts/find_errors.py mismatches/TC_LA_no_ISceI_rep8_seq.txt.gz
python scripts/find_errors.py mismatches/TG_6xPCR_no_ISceI_rep1_seq.txt.gz
python scripts/find_errors.py mismatches/TG_6xPCR_no_ISceI_rep2_seq.txt.gz
python scripts/find_errors.py mismatches/TG_6xPCR_no_ISceI_rep3_seq.txt.gz
python scripts/find_errors.py mismatches/TG_6xPCR_no_ISceI_rep4_seq.txt.gz
python scripts/find_errors.py mismatches/TG_LA_no_ISceI_rep1_seq.txt.gz
python scripts/find_errors.py mismatches/TG_LA_no_ISceI_rep2_seq.txt.gz
python scripts/find_errors.py mismatches/TG_LA_no_ISceI_rep3_seq.txt.gz
python scripts/find_errors.py mismatches/TG_LA_no_ISceI_rep4_seq.txt.gz
