#!/bin/bash

zcat mismatches/AC_6xPCR_no_ISceI_rep1_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_6xPCR_no_ISceI_rep2_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_6xPCR_no_ISceI_rep3_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_6xPCR_no_ISceI_rep4_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_6xPCR_no_ISceI_rep5_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_6xPCR_no_ISceI_rep6_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_6xPCR_no_ISceI_rep7_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_6xPCR_no_ISceI_rep8_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_6xPCR_no_ISceI_rep9_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_LA_no_ISceI_rep1_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_LA_no_ISceI_rep2_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_LA_no_ISceI_rep3_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AC_LA_no_ISceI_rep4_seq.txt.gz | awk '{print "AC", $1}' | sort -u
zcat mismatches/AG_6xPCR_no_ISceI_rep1_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_6xPCR_no_ISceI_rep2_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_6xPCR_no_ISceI_rep3_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_6xPCR_no_ISceI_rep4_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_6xPCR_no_ISceI_rep5_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_6xPCR_no_ISceI_rep6_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_6xPCR_no_ISceI_rep7_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_LA_no_ISceI_rep1_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_LA_no_ISceI_rep2_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_LA_no_ISceI_rep3_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_LA_no_ISceI_rep4_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_LA_no_ISceI_rep5_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_LA_no_ISceI_rep6_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_LA_no_ISceI_rep7_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/AG_LA_no_ISceI_rep8_seq.txt.gz | awk '{print "AG", $1}' | sort -u
zcat mismatches/GT_6xPCR_no_ISceI_rep1_seq.txt.gz | awk '{print "GT", $1}' | sort -u
zcat mismatches/GT_6xPCR_no_ISceI_rep2_seq.txt.gz | awk '{print "GT", $1}' | sort -u
zcat mismatches/GT_6xPCR_no_ISceI_rep3_seq.txt.gz | awk '{print "GT", $1}' | sort -u
zcat mismatches/GT_6xPCR_no_ISceI_rep4_seq.txt.gz | awk '{print "GT", $1}' | sort -u
zcat mismatches/GT_LA_no_ISceI_rep1_seq.txt.gz | awk '{print "GT", $1}' | sort -u
zcat mismatches/GT_LA_no_ISceI_rep2_seq.txt.gz | awk '{print "GT", $1}' | sort -u
zcat mismatches/GT_LA_no_ISceI_rep3_seq.txt.gz | awk '{print "GT", $1}' | sort -u
zcat mismatches/GT_LA_no_ISceI_rep4_seq.txt.gz | awk '{print "GT", $1}' | sort -u
zcat mismatches/TC_6xPCR_no_ISceI_rep1_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_6xPCR_no_ISceI_rep2_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_6xPCR_no_ISceI_rep3_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_6xPCR_no_ISceI_rep4_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_6xPCR_no_ISceI_rep5_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_6xPCR_no_ISceI_rep6_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_6xPCR_no_ISceI_rep7_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_6xPCR_no_ISceI_rep8_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_LA_no_ISceI_rep1_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_LA_no_ISceI_rep2_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_LA_no_ISceI_rep3_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_LA_no_ISceI_rep4_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_LA_no_ISceI_rep5_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_LA_no_ISceI_rep6_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_LA_no_ISceI_rep7_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TC_LA_no_ISceI_rep8_seq.txt.gz | awk '{print "TC", $1}' | sort -u
zcat mismatches/TG_6xPCR_no_ISceI_rep1_seq.txt.gz | awk '{print "TG", $1}' | sort -u
zcat mismatches/TG_6xPCR_no_ISceI_rep2_seq.txt.gz | awk '{print "TG", $1}' | sort -u
zcat mismatches/TG_6xPCR_no_ISceI_rep3_seq.txt.gz | awk '{print "TG", $1}' | sort -u
zcat mismatches/TG_6xPCR_no_ISceI_rep4_seq.txt.gz | awk '{print "TG", $1}' | sort -u
zcat mismatches/TG_LA_no_ISceI_rep1_seq.txt.gz | awk '{print "TG", $1}' | sort -u
zcat mismatches/TG_LA_no_ISceI_rep2_seq.txt.gz | awk '{print "TG", $1}' | sort -u
zcat mismatches/TG_LA_no_ISceI_rep3_seq.txt.gz | awk '{print "TG", $1}' | sort -u
zcat mismatches/TG_LA_no_ISceI_rep4_seq.txt.gz | awk '{print "TG", $1}' | sort -u
