#!/bin/bash

python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_24h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_24h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_24h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_24h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_48h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_48h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_no_ISceI_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_no_ISceI_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_no_ISceI_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_no_ISceI_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_no_ISceI_rep5.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_no_ISceI_rep6.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_6xPCR_no_ISceI_rep7.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_24h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_24h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_24h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_24h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_48h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_48h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_48h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_48h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_no_ISceI_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_no_ISceI_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_no_ISceI_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_no_ISceI_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_no_ISceI_rep5.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_no_ISceI_rep6.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_no_ISceI_rep7.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AG_LA_no_ISceI_rep8.co.gz

python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_24h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_24h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_24h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_24h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_48h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_48h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_48h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_48h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_no_ISceI_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_no_ISceI_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_no_ISceI_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_6xPCR_no_ISceI_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_24h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_24h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_24h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_24h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_48h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_48h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_48h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_48h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_no_ISceI_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_no_ISceI_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_no_ISceI_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TG_LA_no_ISceI_rep4.co.gz

python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_24h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_24h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_24h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_24h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_48h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_48h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_48h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_48h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_no_ISceI_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_no_ISceI_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_no_ISceI_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_no_ISceI_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_no_ISceI_rep5.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_no_ISceI_rep6.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_no_ISceI_rep7.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_no_ISceI_rep8.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_6xPCR_no_ISceI_rep9.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_24h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_24h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_24h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_24h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_48h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_48h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_48h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_48h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_no_ISceI_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_no_ISceI_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_no_ISceI_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/AC_LA_no_ISceI_rep4.co.gz

python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_24h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_24h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_24h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_24h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_48h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_48h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_48h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_48h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_no_ISceI_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_no_ISceI_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_no_ISceI_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_no_ISceI_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_no_ISceI_rep5.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_no_ISceI_rep6.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_no_ISceI_rep7.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_6xPCR_no_ISceI_rep8.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_24h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_24h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_24h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_48h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_48h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_48h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_48h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_no_ISceI_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_no_ISceI_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_no_ISceI_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_no_ISceI_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_no_ISceI_rep5.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_no_ISceI_rep6.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_no_ISceI_rep7.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/TC_LA_no_ISceI_rep8.co.gz

python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_24h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_24h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_24h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_24h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_48h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_48h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_48h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_48h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_no_ISceI_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_no_ISceI_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_no_ISceI_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_6xPCR_no_ISceI_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_24h_rep1.co.gz   
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_24h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_24h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_24h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_48h_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_48h_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_48h_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_48h_rep4.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_no_ISceI_rep1.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_no_ISceI_rep2.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_no_ISceI_rep3.co.gz
python scripts/make_events_without_mapping.py black.lst.gz mismatches/GT_LA_no_ISceI_rep4.co.gz
